/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as UsernameIndexRouteImport } from './routes/$username/index'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as UsernameSlugIndexRouteImport } from './routes/$username/$slug/index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as UsernameSlugCancelBookingIdRouteImport } from './routes/$username/$slug/cancel/$bookingId'
import { Route as UsernameSlugConfirmedBookingIdRouteImport } from './routes/$username/$slug/confirmed/$bookingId'
import { Route as UsernameSlugRescheduleBookingIdRouteImport } from './routes/$username/$slug/reschedule/$bookingId'
import { Route as AuthenticatedDashboardAnalyticsIndexRouteImport } from './routes/_authenticated/dashboard/analytics/index'
import { Route as AuthenticatedDashboardAvailabilityIndexRouteImport } from './routes/_authenticated/dashboard/availability/index'
import { Route as AuthenticatedDashboardBookingsIndexRouteImport } from './routes/_authenticated/dashboard/bookings/index'
import { Route as AuthenticatedDashboardEventTypesIndexRouteImport } from './routes/_authenticated/dashboard/event-types/index'
import { Route as AuthenticatedDashboardEventTypesIdRouteImport } from './routes/_authenticated/dashboard/event-types/$id'
import { Route as AuthenticatedDashboardEventTypesNewRouteImport } from './routes/_authenticated/dashboard/event-types/new'
import { Route as AuthenticatedDashboardIntegrationsIndexRouteImport } from './routes/_authenticated/dashboard/integrations/index'
import { Route as AuthenticatedDashboardSettingsIndexRouteImport } from './routes/_authenticated/dashboard/settings/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const UsernameIndexRoute = UsernameIndexRouteImport.update({
  id: '/$username/',
  path: '/$username/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const UsernameSlugIndexRoute = UsernameSlugIndexRouteImport.update({
  id: '/$username/$slug/',
  path: '/$username/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const UsernameSlugCancelBookingIdRoute =
  UsernameSlugCancelBookingIdRouteImport.update({
    id: '/$username/$slug/cancel/$bookingId',
    path: '/$username/$slug/cancel/$bookingId',
    getParentRoute: () => rootRouteImport,
  } as any)
const UsernameSlugConfirmedBookingIdRoute =
  UsernameSlugConfirmedBookingIdRouteImport.update({
    id: '/$username/$slug/confirmed/$bookingId',
    path: '/$username/$slug/confirmed/$bookingId',
    getParentRoute: () => rootRouteImport,
  } as any)
const UsernameSlugRescheduleBookingIdRoute =
  UsernameSlugRescheduleBookingIdRouteImport.update({
    id: '/$username/$slug/reschedule/$bookingId',
    path: '/$username/$slug/reschedule/$bookingId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedDashboardAnalyticsIndexRoute =
  AuthenticatedDashboardAnalyticsIndexRouteImport.update({
    id: '/dashboard/analytics/',
    path: '/dashboard/analytics/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardAvailabilityIndexRoute =
  AuthenticatedDashboardAvailabilityIndexRouteImport.update({
    id: '/dashboard/availability/',
    path: '/dashboard/availability/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardBookingsIndexRoute =
  AuthenticatedDashboardBookingsIndexRouteImport.update({
    id: '/dashboard/bookings/',
    path: '/dashboard/bookings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardEventTypesIndexRoute =
  AuthenticatedDashboardEventTypesIndexRouteImport.update({
    id: '/dashboard/event-types/',
    path: '/dashboard/event-types/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardEventTypesIdRoute =
  AuthenticatedDashboardEventTypesIdRouteImport.update({
    id: '/dashboard/event-types/$id',
    path: '/dashboard/event-types/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardEventTypesNewRoute =
  AuthenticatedDashboardEventTypesNewRouteImport.update({
    id: '/dashboard/event-types/new',
    path: '/dashboard/event-types/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardIntegrationsIndexRoute =
  AuthenticatedDashboardIntegrationsIndexRouteImport.update({
    id: '/dashboard/integrations/',
    path: '/dashboard/integrations/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardSettingsIndexRoute =
  AuthenticatedDashboardSettingsIndexRouteImport.update({
    id: '/dashboard/settings/',
    path: '/dashboard/settings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/invite/$token': typeof InviteTokenRoute
  '/$username/': typeof UsernameIndexRoute
  '/$username/$slug/': typeof UsernameSlugIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/$username/$slug/cancel/$bookingId': typeof UsernameSlugCancelBookingIdRoute
  '/$username/$slug/confirmed/$bookingId': typeof UsernameSlugConfirmedBookingIdRoute
  '/$username/$slug/reschedule/$bookingId': typeof UsernameSlugRescheduleBookingIdRoute
  '/dashboard/event-types/$id': typeof AuthenticatedDashboardEventTypesIdRoute
  '/dashboard/event-types/new': typeof AuthenticatedDashboardEventTypesNewRoute
  '/dashboard/analytics/': typeof AuthenticatedDashboardAnalyticsIndexRoute
  '/dashboard/availability/': typeof AuthenticatedDashboardAvailabilityIndexRoute
  '/dashboard/bookings/': typeof AuthenticatedDashboardBookingsIndexRoute
  '/dashboard/event-types/': typeof AuthenticatedDashboardEventTypesIndexRoute
  '/dashboard/integrations/': typeof AuthenticatedDashboardIntegrationsIndexRoute
  '/dashboard/settings/': typeof AuthenticatedDashboardSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/invite/$token': typeof InviteTokenRoute
  '/$username': typeof UsernameIndexRoute
  '/$username/$slug': typeof UsernameSlugIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/$username/$slug/cancel/$bookingId': typeof UsernameSlugCancelBookingIdRoute
  '/$username/$slug/confirmed/$bookingId': typeof UsernameSlugConfirmedBookingIdRoute
  '/$username/$slug/reschedule/$bookingId': typeof UsernameSlugRescheduleBookingIdRoute
  '/dashboard/event-types/$id': typeof AuthenticatedDashboardEventTypesIdRoute
  '/dashboard/event-types/new': typeof AuthenticatedDashboardEventTypesNewRoute
  '/dashboard/analytics': typeof AuthenticatedDashboardAnalyticsIndexRoute
  '/dashboard/availability': typeof AuthenticatedDashboardAvailabilityIndexRoute
  '/dashboard/bookings': typeof AuthenticatedDashboardBookingsIndexRoute
  '/dashboard/event-types': typeof AuthenticatedDashboardEventTypesIndexRoute
  '/dashboard/integrations': typeof AuthenticatedDashboardIntegrationsIndexRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/invite/$token': typeof InviteTokenRoute
  '/$username/': typeof UsernameIndexRoute
  '/$username/$slug/': typeof UsernameSlugIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/$username/$slug/cancel/$bookingId': typeof UsernameSlugCancelBookingIdRoute
  '/$username/$slug/confirmed/$bookingId': typeof UsernameSlugConfirmedBookingIdRoute
  '/$username/$slug/reschedule/$bookingId': typeof UsernameSlugRescheduleBookingIdRoute
  '/_authenticated/dashboard/event-types/$id': typeof AuthenticatedDashboardEventTypesIdRoute
  '/_authenticated/dashboard/event-types/new': typeof AuthenticatedDashboardEventTypesNewRoute
  '/_authenticated/dashboard/analytics/': typeof AuthenticatedDashboardAnalyticsIndexRoute
  '/_authenticated/dashboard/availability/': typeof AuthenticatedDashboardAvailabilityIndexRoute
  '/_authenticated/dashboard/bookings/': typeof AuthenticatedDashboardBookingsIndexRoute
  '/_authenticated/dashboard/event-types/': typeof AuthenticatedDashboardEventTypesIndexRoute
  '/_authenticated/dashboard/integrations/': typeof AuthenticatedDashboardIntegrationsIndexRoute
  '/_authenticated/dashboard/settings/': typeof AuthenticatedDashboardSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/features'
    | '/forgot-password'
    | '/onboarding'
    | '/pricing'
    | '/reset-password'
    | '/invite/$token'
    | '/$username/'
    | '/$username/$slug/'
    | '/dashboard/'
    | '/$username/$slug/cancel/$bookingId'
    | '/$username/$slug/confirmed/$bookingId'
    | '/$username/$slug/reschedule/$bookingId'
    | '/dashboard/event-types/$id'
    | '/dashboard/event-types/new'
    | '/dashboard/analytics/'
    | '/dashboard/availability/'
    | '/dashboard/bookings/'
    | '/dashboard/event-types/'
    | '/dashboard/integrations/'
    | '/dashboard/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/features'
    | '/forgot-password'
    | '/onboarding'
    | '/pricing'
    | '/reset-password'
    | '/invite/$token'
    | '/$username'
    | '/$username/$slug'
    | '/dashboard'
    | '/$username/$slug/cancel/$bookingId'
    | '/$username/$slug/confirmed/$bookingId'
    | '/$username/$slug/reschedule/$bookingId'
    | '/dashboard/event-types/$id'
    | '/dashboard/event-types/new'
    | '/dashboard/analytics'
    | '/dashboard/availability'
    | '/dashboard/bookings'
    | '/dashboard/event-types'
    | '/dashboard/integrations'
    | '/dashboard/settings'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/features'
    | '/forgot-password'
    | '/onboarding'
    | '/pricing'
    | '/reset-password'
    | '/invite/$token'
    | '/$username/'
    | '/$username/$slug/'
    | '/_authenticated/dashboard/'
    | '/$username/$slug/cancel/$bookingId'
    | '/$username/$slug/confirmed/$bookingId'
    | '/$username/$slug/reschedule/$bookingId'
    | '/_authenticated/dashboard/event-types/$id'
    | '/_authenticated/dashboard/event-types/new'
    | '/_authenticated/dashboard/analytics/'
    | '/_authenticated/dashboard/availability/'
    | '/_authenticated/dashboard/bookings/'
    | '/_authenticated/dashboard/event-types/'
    | '/_authenticated/dashboard/integrations/'
    | '/_authenticated/dashboard/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  FeaturesRoute: typeof FeaturesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  InviteTokenRoute: typeof InviteTokenRoute
  UsernameIndexRoute: typeof UsernameIndexRoute
  UsernameSlugIndexRoute: typeof UsernameSlugIndexRoute
  UsernameSlugCancelBookingIdRoute: typeof UsernameSlugCancelBookingIdRoute
  UsernameSlugConfirmedBookingIdRoute: typeof UsernameSlugConfirmedBookingIdRoute
  UsernameSlugRescheduleBookingIdRoute: typeof UsernameSlugRescheduleBookingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username/': {
      id: '/$username/'
      path: '/$username'
      fullPath: '/$username/'
      preLoaderRoute: typeof UsernameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username/$slug/': {
      id: '/$username/$slug/'
      path: '/$username/$slug'
      fullPath: '/$username/$slug/'
      preLoaderRoute: typeof UsernameSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/$username/$slug/cancel/$bookingId': {
      id: '/$username/$slug/cancel/$bookingId'
      path: '/$username/$slug/cancel/$bookingId'
      fullPath: '/$username/$slug/cancel/$bookingId'
      preLoaderRoute: typeof UsernameSlugCancelBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username/$slug/confirmed/$bookingId': {
      id: '/$username/$slug/confirmed/$bookingId'
      path: '/$username/$slug/confirmed/$bookingId'
      fullPath: '/$username/$slug/confirmed/$bookingId'
      preLoaderRoute: typeof UsernameSlugConfirmedBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username/$slug/reschedule/$bookingId': {
      id: '/$username/$slug/reschedule/$bookingId'
      path: '/$username/$slug/reschedule/$bookingId'
      fullPath: '/$username/$slug/reschedule/$bookingId'
      preLoaderRoute: typeof UsernameSlugRescheduleBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/analytics/': {
      id: '/_authenticated/dashboard/analytics/'
      path: '/dashboard/analytics'
      fullPath: '/dashboard/analytics/'
      preLoaderRoute: typeof AuthenticatedDashboardAnalyticsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/availability/': {
      id: '/_authenticated/dashboard/availability/'
      path: '/dashboard/availability'
      fullPath: '/dashboard/availability/'
      preLoaderRoute: typeof AuthenticatedDashboardAvailabilityIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/bookings/': {
      id: '/_authenticated/dashboard/bookings/'
      path: '/dashboard/bookings'
      fullPath: '/dashboard/bookings/'
      preLoaderRoute: typeof AuthenticatedDashboardBookingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/event-types/': {
      id: '/_authenticated/dashboard/event-types/'
      path: '/dashboard/event-types'
      fullPath: '/dashboard/event-types/'
      preLoaderRoute: typeof AuthenticatedDashboardEventTypesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/event-types/$id': {
      id: '/_authenticated/dashboard/event-types/$id'
      path: '/dashboard/event-types/$id'
      fullPath: '/dashboard/event-types/$id'
      preLoaderRoute: typeof AuthenticatedDashboardEventTypesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/event-types/new': {
      id: '/_authenticated/dashboard/event-types/new'
      path: '/dashboard/event-types/new'
      fullPath: '/dashboard/event-types/new'
      preLoaderRoute: typeof AuthenticatedDashboardEventTypesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/integrations/': {
      id: '/_authenticated/dashboard/integrations/'
      path: '/dashboard/integrations'
      fullPath: '/dashboard/integrations/'
      preLoaderRoute: typeof AuthenticatedDashboardIntegrationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/settings/': {
      id: '/_authenticated/dashboard/settings/'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardEventTypesIdRoute: typeof AuthenticatedDashboardEventTypesIdRoute
  AuthenticatedDashboardEventTypesNewRoute: typeof AuthenticatedDashboardEventTypesNewRoute
  AuthenticatedDashboardAnalyticsIndexRoute: typeof AuthenticatedDashboardAnalyticsIndexRoute
  AuthenticatedDashboardAvailabilityIndexRoute: typeof AuthenticatedDashboardAvailabilityIndexRoute
  AuthenticatedDashboardBookingsIndexRoute: typeof AuthenticatedDashboardBookingsIndexRoute
  AuthenticatedDashboardEventTypesIndexRoute: typeof AuthenticatedDashboardEventTypesIndexRoute
  AuthenticatedDashboardIntegrationsIndexRoute: typeof AuthenticatedDashboardIntegrationsIndexRoute
  AuthenticatedDashboardSettingsIndexRoute: typeof AuthenticatedDashboardSettingsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedDashboardEventTypesIdRoute:
    AuthenticatedDashboardEventTypesIdRoute,
  AuthenticatedDashboardEventTypesNewRoute:
    AuthenticatedDashboardEventTypesNewRoute,
  AuthenticatedDashboardAnalyticsIndexRoute:
    AuthenticatedDashboardAnalyticsIndexRoute,
  AuthenticatedDashboardAvailabilityIndexRoute:
    AuthenticatedDashboardAvailabilityIndexRoute,
  AuthenticatedDashboardBookingsIndexRoute:
    AuthenticatedDashboardBookingsIndexRoute,
  AuthenticatedDashboardEventTypesIndexRoute:
    AuthenticatedDashboardEventTypesIndexRoute,
  AuthenticatedDashboardIntegrationsIndexRoute:
    AuthenticatedDashboardIntegrationsIndexRoute,
  AuthenticatedDashboardSettingsIndexRoute:
    AuthenticatedDashboardSettingsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  FeaturesRoute: FeaturesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  InviteTokenRoute: InviteTokenRoute,
  UsernameIndexRoute: UsernameIndexRoute,
  UsernameSlugIndexRoute: UsernameSlugIndexRoute,
  UsernameSlugCancelBookingIdRoute: UsernameSlugCancelBookingIdRoute,
  UsernameSlugConfirmedBookingIdRoute: UsernameSlugConfirmedBookingIdRoute,
  UsernameSlugRescheduleBookingIdRoute: UsernameSlugRescheduleBookingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
